### ISSUE TITLE
Documentation out-of-date?

### ISSUE THREAD

**Issue by gkop** [thisismydesign/json-streamer#1]
Awesome library! Ruby deserves such a simple streaming JSON parser. Thanks for making this.

The README at the time I am creating this issue says to use

```ruby
streamer.get(key:'key').each do |object|
```

However I am finding the API is actually

```ruby
streamer.get(key:'key') do |object|
```

Incidentally, this is related to a suggestion that I have to make the API even nicer and more Ruby-ish:

```ruby
streamer.get(key:'key') # when not passed a block, this should return an instance of Enumerator
```

Alternatively, if that's not easy to accomplish, this would be an acceptable alternative:

```ruby
streamer.get(key:'key').to_enum
```

**Comment by thisismydesign** [comment]
Thanks for the feedback!

You're right, thanks for pointing that out. I will update the README and revert back to you about the possible API improvement as well.

**Comment by thisismydesign** [comment]
The documentation have been fixed. I've created a [separate issue](https://github.com/thisismydesign/json-streamer/issues/2) for the API changes.
