### ISSUE TITLE
What is the point of `yield_values: false`?

### ISSUE THREAD

**Issue by machty** [thisismydesign/json-streamer#16]
Maybe this is just something that needs a README tweak, but what is `yield_values: false` doing? Isn't the whole point of the API to yield parsed values?

Or... is it saying: "don't yield primitive values, only yield objects and arrays"? If so, why is that useful?

**Comment by thisismydesign** [comment]
> don't yield primitive values, only yield objects and arrays

Yep, that's it.

> If so, why is that useful?

I found it useful but I admit it's very use-case dependent.

**Comment by thisismydesign** [comment]
Btw, the terminology comes from the parsers, that distinguish between values, objects, and arrays, see: https://github.com/thisismydesign/json-streamer/blob/69a48496d811efbd5a8ba211314d6cc6f0ddb78d/lib/json/streamer/parser.rb
