### ISSUE TITLE
Iterating over a list of objects

### ISSUE THREAD

**Issue by whitewolf92** [thisismydesign/json-streamer#17]
Hi Csaba, 

Just want to check with you. How can I parse and display the following json? I tried many ways but doesn't seem to get the output that I want.

```json
{
  "meta": "first_level_value",
  "data": {
    "1111-2222": { "low_price": 1.2, "high_price": 1.2 },
    "3333-4444": { "low_price": 1.3, "high_price": 2.2 },
    "4444-5555": { "low_price": 1.4, "high_price": 3.2 }
  }
}
```

I need to iterate the **data** list and print each row by their key and value.

```json
"1111-2222": { "low_price": 1.2, "high_price": 1.2 }
"3333-4444": { "low_price": 1.3, "high_price": 2.2 }
"4444-5555": { "low_price": 1.4, "high_price": 3.2 }
```

Is there a way to do the above? Thanks

**Comment by thisismydesign** [comment]
Hey, this is possible via a custom event generator as seen in the readme. For support/questions please use stackoverflow.
