### ISSUE TITLE
Symbolize Keys

### ISSUE THREAD

**Issue by eggie5** [thisismydesign/json-streamer#6]
I would suggest adding a symbolize keys options like yajl. Here are memory arguments in favor of this in ruby:

"Doing so is much more efficient for parsing JSON streams with lots of repetitive keys - for things like result sets or multiple API requests - than the same parse with string keys. This is because Ruby will reuse (and never GC) its symbol table."

**Comment by thisismydesign** [comment]
Sounds like a good improvement.

**Comment by thisismydesign** [comment]
Feature added in [v1.3.0](https://github.com/thisismydesign/json-streamer/releases/tag/v1.3.0). Thanks for the suggestion!

Just a small FYI: newer versions of [Ruby (2.2+) do GC symbols](https://www.sitepoint.com/symbol-gc-ruby-2-2/).
